Serilog:
  Using:
    - Serilog.Sinks.Console
    # - Serilog.Sinks.File
    # - Serilog.Sinks.Grafana.Loki
  MinimumLevel:
    Default: Information
    Override:
      Microsoft: Warning
      Microsoft.Hosting.Lifetime: Information
      Microsoft.EntityFrameworkCore.Database.Command: Warning
  WriteTo:
    - Name: Console
      Args:
        outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj}{NewLine}{Exception}"
    # - Name: File
    #   Args:
    #     path: ./data/logs/hd-.log
    #     rollingInterval: Day
    #     outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj}{NewLine}{Exception}"
    # - Name: GrafanaLoki
    #   Args:
    #     uri: http://localhost:3100
    #     labels:
    #       - key: app
    #         value: hyper-dimension
    #     propertiesAsLabels:
    #       - app

Database:
  Type: SQLite                                                        # SQLite, SQLServer, PostgreSQL, MySQL
  ConnectionString: "Data Source=data/HyperDimension.db;Version=3;    # Check out: connectionstrings.com

Storage:
  Type: FileSystem                    # FileSystem, S3

  FileSystem:
    RootPath: ./data/blob

  S3:
    Flavor: Generic                   # Generic, Amazon
    Endpoint: http://localhost:9000   # Only for Generic
    AccessKey: minio                  # Both
    SecretKey: minio123               # Both
    BucketName: hyper-dimension       # Both
    Region: ap-east-1                 # Both
    ForcePathStyle: true              # Only for Generic

Cache:
  Type: Memory

  Memory:
    Size: 1024                        # In MB

  Redis:
    ConnectionString: localhost:6379
    Database: 0
    KeyPrefix: hd-
