Serilog:
  Using:
    - Serilog.Sinks.Console
  MinimumLevel:
    Default: Information
    Override:
      Microsoft: Warning
      Microsoft.Hosting.Lifetime: Information
      Microsoft.EntityFrameworkCore.Database.Command: Warning
  WriteTo:
    - Name: Console
      Args:
        outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj}{NewLine}{Exception}"

Database:
  Type: SQLite
  ConnectionString: "Data Source=data/HyperDimension.db;Version=3;
  SQLServer:
    CompatibilityVersion: 160

